---
compilers:
  :dev_kit:
    :name: DevKit
    :url: "http://cloud.github.com/downloads/oneclick/rubyinstaller/DevKit-tdm-32-4.5.1-20101214-1400-sfx.exe"

components:
  :git:
    :name: Git
    :url: "http://code.google.com/p/msysgit/downloads/detail?name=Git-1.7.3.1-preview20101002.exe"

  :mysql:
    :name: Mysql
    :dlls:
      - mysql/lib/libmysql.dll
    :configure:
      - --with-mysql-config="{{stage_path}}/mysql/bin/mysql_config"

  :mysql_server:
    :name: MySQLServer
    :url: "http://mysql.mirrors.pair.com/Downloads/MySQL-5.5/mysql-5.5.8-winx64.zip"
    :urls:
      - "http://mysql.mirrors.pair.com/Downloads/MySQL-5.5/mysql-5.5.8-winx64.zip"
      - "http://mysql.mirrors.pair.com/Downloads/MySQL-5.5/mysql-5.5.8-winx32.zip"

  :pg:
    :name: Pg
    :dlls:
      - postgresql/lib/libpq.dll
    :configure:
      - --with-pg-config="{{stage_path}}/postgresql/bin/pg_config"

  :postgresql_server:
    :name: PostgreSQLServer
    :url: "http://get.enterprisedb.com/postgresql/postgresql-9.0.2-1-windows_x64-binaries.zip"

  :rails:
    :name: Rails

  :rails_docs:
    :name: RailsDocs

  :rails_guides:
    :name: RailsGuides

  :ruby_docs:
    :name: RubyDocs

  :ruby_installer:
    :name: RubyInstaller
    :default_version: 1.8.7-p330
    :versions:
      1.9.2-p136: "http://files.rubyforge.vm.bytemark.co.uk/rubyinstaller/ruby-1.9.2-p136-i386-mingw32.7z"
      1.8.7-p330: "http://files.rubyforge.vm.bytemark.co.uk/rubyinstaller/ruby-1.8.7-p330-i386-mingw32.7z"

  :editor:
    :name: Editor

  :rubygems:
    :name: RubyGems

  :sqlite3:
    :name: Sqlite3

  :sqlserver:
    :name: SqlServer

  :ssl_certificates:
    :name: SSLCertificates
    :url: http://curl.haxx.se/ca
    :file: cacert.pem

  :subversion:
    :name: Subversion

utilities:

  :bsdtar:
    :name: BSDTar
    :type: utility
    :binary: basic-bsdtar.exe
    :location: sandbox
    :url: "http://downloads.sourceforge.net/mingw/basic-bsdtar-2.8.3-1-mingw32-bin.zip"

  :sevenzip:
    :name: SevenZip
    :type: utility
    :binary: 7za.exe
    :location: sandbox
    :url: "http://voxel.dl.sourceforge.net/project/sevenzip/7-Zip/9.20/7za920.zip"

