---
:name: DevKit
:installer_guid: "{D25478D4-72AE-40BF-829F-2C8CE49E2EE8}"
:install_script: resources/devkit/dk.rb
:install_script_erb: resources/devkit/dk.rb.erb
:inno_script: resources/devkit/devkit.iss
:inno_config: resources/devkit/dk_config.iss
:inno_config_erb: resources/devkit/dk_config.iss.erb
:setup_scripts:
  - devkitvars.bat
  - devkitvars.ps1
  - dk.rb
:default_compiler: tdm-32-4.5.1
:valid_compilers:
  - tdm-32-4.5.1
  - tdm-32-4.5.0
  - tdm-64-4.5.1
  - llvm-32-2.8
  - mingw-32-3.4.5
